#!/usr/bin/env bash
# Bash script with multiple executions

echo "$$" > /var/run/alxcript.pid
while true
do
	echo "To infinity and beyond"
	sleep 0.5
	trap 'echo "I hate the kill command"; rm /var/run/alxscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/alxscript.pid; exit' SIGQUIT
done
